name: Check
on: [push, pull_request]
jobs:
  src:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - name: Format src
      run: cargo fmt --all -- --check

    - name: Clippy src (no default features, hashbrown)
      run: cargo clippy --no-default-features --features hashbrown -- -D warnings

    - name: Clippy src (all features)
      run: cargo clippy --all-features -- -D warnings

  dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy
        override: true

    - name: Format dev
      run: cargo fmt --all -- --check
      working-directory: ./dev

    - name: Clippy dev (all features)
      run: cargo clippy --all-features -- -D warnings
      working-directory: ./dev
